### ISSUE TITLE
where to put I18n.backend = I18n::Backend::SideBySide.new?

### ISSUE THREAD

**Issue by dedles** [electric-feel/i18n-backend-side_by_side#4]
Sorry if this is a newb question, but where are you supposed to put
 'I18n.backend = I18n::Backend::SideBySide.new'?

**Comment by dedles** [comment]
Also I'm getting the error "undefined method `first' for nil:NilClass" for all my old translation keys. My yml file passes as valid yaml at http://www.yamllint.com/.
my yml file looks like this: https://gist.github.com/dedles/1cc4a0e74f7d0e1fee91

and I'm calling a translation like this: <%= t('layouts.navbar.languages.language') %> or like this: <%= link_to t('.about'), about_path %>

**Comment by fphilipe** [comment]
Your YAML file looks correct. The error you're seeing is probably because you haven't set up the gem correctly. To do so, just put that line in a rails initializer, i.e. create a file `config/initializers/i18n.rb` with the content `I18n.backend = I18n::Backend::SideBySide.new`. Hope this helps.
